xbrlOptions = {
    'dei': {
        'EntityRegistrantName': ['entityregistrantname'],
        'CurrentFiscalYearEndDate': ['currentfiscalyearenddate'],
        'CIK': ['entitycentralindexkey'],
        'Ticker': ['tradingsymbol'],
        'DocumentPeriodEndDate': ['documentperiodenddate'],
        'DocumentFiscalYearFocus': ['documentfiscalyearfocus'],
        'DocumentFiscalPeriodFocus': ['documentfiscalperiodfocus'],
        'DocumentFiscalYearFocusContext': [{'documentfiscalyearfocus': 'contextref'}],
        'DocumentFiscalPeriodFocusContext': [{'DocumentFiscalPeriodFocus': 'contextref'}],
        'DocumentType': ['documenttype'],
        'OutstandingShares': ['entitycommonstocksharesoutstanding'],
    },
    'us-gaap': {
        'Assets': ['assets'],
        'CurrentAssets': ['assetscurrent'],
        'NoncurrentAssets': ['assetsnoncurrent'],
        'LiabilitiesAndEquity': ['liabilitiesandstockholdersequity'],
        'Liabilities': ['Liabilities'],
        'CurrentLiabilities': ['liabilitiescurrent'],
        'NoncurrentLiabilities': ['liabilitiesnoncurrent'],
        'CommitmentsAndContingencies': ['commitmentsandcontingencies'],
        'TemporaryEquity': ['TemporaryEquityRedemptionValue', 'RedeemablePreferredStockCarryingAmount', 'TemporaryEquityCarryingAmount', 'TemporaryEquityValueExcludingAdditionalPaidInCapital', 'TemporaryEquityCarryingAmountAttributableToParent', 'RedeemableNoncontrollingInterestEquityFairValue'],
        'Equity': ['stockholdersequity', 'StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest', 'PartnersCapitalIncludingPortionAttributableToNoncontrollingInterest', 'PartnersCapital', 'CommonStockholdersEquity', 'MemberEquity', 'AssetsNet'],
        'EquityAttributableToNoncontrollingInterest': ['MinorityInterest', 'PartnersCapitalAttributableToNoncontrollingInterest'],
        'Revenues': ['Revenues', 'SalesRevenueNet', 'SalesRevenueServicesNet', 'RevenuesNetOfInterestExpense', 'RegulatedAndUnregulatedOperatingRevenue', 'HealthCareOrganizationRevenue', 'InterestAndDividendIncomeOperating', 'RealEstateRevenueNet', 'RevenueMineralSales', 'OilAndGasRevenue', 'FinancialServicesRevenue', 'RegulatedAndUnregulatedOperatingRevenue'],
        'CostOfRevenue': ['costofgoodsandservicessold', 'CostOfRevenue', 'CostOfServices', 'CostOfGoodsSold', 'CostOfGoodsAndServicesSold'],
        'GrossProfit': ['GrossProfit'],
        'OperatingExpenses': ['OperatingExpenses', 'OperatingCostsAndExpenses'],
        'CostsAndExpenses': ['CostsAndExpenses'],
        'OtherOperatingIncome': ['OtherOperatingIncome'],
        'OperatingIncomeLoss': ['OperatingIncomeLoss'],
        'NonoperatingIncomeLoss': ['NonoperatingIncomeExpense'],
        'InterestAndDebtExpense': ['interestexpensedebt', 'InterestAndDebtExpense'],
        'IncomeBeforeEquityMethodInvestments': ['IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments'],
        'IncomeFromEquityMethodInvestments': ['IncomeLossFromEquityMethodInvestments'],
        'IncomeFromContinuingOperationsBeforeTax': ['IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments', 'IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest'],
        'IncomeTaxExpenseBenefit': ['IncomeTaxExpenseBenefit', 'IncomeTaxExpenseBenefitContinuingOperations'],
        'IncomeFromContinuingOperationsAfterTax': ['IncomeLossBeforeExtraordinaryItemsAndCumulativeEffectOfChangeInAccountingPrinciple'],
        'IncomeFromDiscontinuedOperations': ['IncomeLossFromDiscontinuedOperationsNetOfTax', 'DiscontinuedOperationGainLossOnDisposalOfDiscontinuedOperationNetOfTax', 'IncomeLossFromDiscontinuedOperationsNetOfTaxAttributableToReportingEntity'],
        'ExtraordaryItemsGainLoss': ['ExtraordinaryItemNetOfTax'],
        'NetIncomeLoss': ['NetIncomeLoss', 'ProfitLoss', 'NetIncomeLossAvailableToCommonStockholdersBasic', 'IncomeLossFromContinuingOperations', 'IncomeLossAttributableToParent', 'IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest'],
        'NetIncomeAvailableToCommonStockholdersBasic': ['NetIncomeLossAvailableToCommonStockholdersBasic'],
        'PreferredStockDividendsAndOtherAdjustments': ['PreferredStockDividendsAndOtherAdjustments'],
        'NetIncomeAttributableToNoncontrollingInterest': ['NetIncomeLossAttributableToNoncontrollingInterest'],
        'NetIncomeAttributableToParent': ['NetIncomeLoss'],
        'OtherComprehensiveIncome': ['OtherComprehensiveIncomeLossNetOfTax'],
        'ComprehensiveIncome': ['ComprehensiveIncomeNetOfTaxIncludingPortionAttributableToNoncontrollingInterest', 'ComprehensiveIncomeNetOfTax'],
        'ComprehensiveIncomeAttributableToParent': ['ComprehensiveIncomeNetOfTax'],
        'ComprehensiveIncomeAttributableToNoncontrollingInterest': ['ComprehensiveIncomeNetOfTaxIncludingPortionAttributableToNoncontrollingInterest'],
        'NetCashFlow': ['CashAndCashEquivalentsPeriodIncreaseDecrease', 'CashPeriodIncreaseDecrease', 'NetCashProvidedByUsedInContinuingOperations'],
        'NetCashFlowsOperating': ['NetCashProvidedByUsedInOperatingActivities'],
        'NetCashFlowsInvesting': ['NetCashProvidedByUsedInInvestingActivities'],
        'NetCashFlowsFinancing': ['NetCashProvidedByUsedInFinancingActivities'],
        'NetCashFlowsOperatingContinuing': ['NetCashProvidedByUsedInOperatingActivitiesContinuingOperations'],
        'NetCashFlowsInvestingContinuing': ['NetCashProvidedByUsedInInvestingActivitiesContinuingOperations'],
        'NetCashFlowsFinancingContinuing': ['NetCashProvidedByUsedInFinancingActivitiesContinuingOperations'],
        'NetCashFlowsOperatingDiscontinued': ['CashProvidedByUsedInOperatingActivitiesDiscontinuedOperations'],
        'NetCashFlowsInvestingDiscontinued': ['CashProvidedByUsedInInvestingActivitiesDiscontinuedOperations'],
        'NetCashFlowsFinancingDiscontinued': ['CashProvidedByUsedInFinancingActivitiesDiscontinuedOperations'],
        'NetCashFlowsDiscontinued': ['NetCashProvidedByUsedInDiscontinuedOperations'],
        'ExchangeGainsLosses': ['EffectOfExchangeRateOnCashAndCashEquivalents', 'EffectOfExchangeRateOnCashAndCashEquivalentsContinuingOperations', 'CashProvidedByUsedInFinancingActivitiesDiscontinuedOperations'],
        'Dividends': ['dividends'],
        'EPS': ['earningspersharebasic', 'EarningsPerShare']
    },
    'calc': {
        'SGR': 0,
        'ROA': 0,
        'ROE': 0,
        'ROS': 0,
        'DE': 0
    },
    'unknown': {
        'BalanceSheetDate': False,
        'ContextForDurations': False,
        'IncomeStatementPeriodYTD': False,
        'ContextForInstants': False,
        'EquityAttributableToParent': 0,
        'NonoperatingIncomeLossPlusInterestAndDebtExpense': 0,
        'NonoperatingIncomePlusInterestAndDebtExpensePlusIncomeFromEquityMethodInvestments': 0,
        'NetCashFlowsContinuing': [''],
    },
}

companyPrototype = {
    'dei': {
        'EntityRegistrantName': False,
        'CurrentFiscalYearEndDate': False,
        'CIK': False,
        'Ticker': False,
        'DocumentPeriodEndDate': False,
        'DocumentFiscalYearFocus': False,
        'DocumentFiscalPeriodFocus': False,
        'DocumentFiscalYearFocusContext': False,
        'DocumentFiscalPeriodFocusContext': False,
        'DocumentType': False,
        'OutstandingShares': False,
    },
    'us-gaap': {
        'Assets': False,
        'CurrentAssets': False,
        'NoncurrentAssets': False,
        'LiabilitiesAndEquity': False,
        'Liabilities': False,
        'CurrentLiabilities': False,
        'NoncurrentLiabilities': False,
        'CommitmentsAndContingencies': False,
        'Equity': False,
        'EquityAttributableToNoncontrollingInterest': False,
        'Revenues': False,
        'CostOfRevenue': False,
        'GrossProfit': False,
        'OperatingExpenses': False,
        'CostsAndExpenses': False,
        'OtherOperatingIncome': False,
        'OperatingIncomeLoss': False,
        'NonoperatingIncomeLoss': False,
        'InterestAndDebtExpense': False,
        'IncomeBeforeEquityMethodInvestments': False,
        'IncomeFromEquityMethodInvestments': False,
        'IncomeFromContinuingOperationsBeforeTax': False,
        'IncomeTaxExpenseBenefit': False,
        'IncomeFromContinuingOperationsAfterTax': False,
        'IncomeFromDiscontinuedOperations': False,
        'ExtraordaryItemsGainLoss': False,
        'NetIncomeLoss': False,
        'NetIncomeAvailableToCommonStockholdersBasic': False,
        'PreferredStockDividendsAndOtherAdjustments': False,
        'NetIncomeAttributableToNoncontrollingInterest': False,
        'NetIncomeAttributableToParent': False,
        'OtherComprehensiveIncome': False,
        'ComprehensiveIncome': False,
        'ComprehensiveIncomeAttributableToParent': False,
        'ComprehensiveIncomeAttributableToNoncontrollingInterest': False,
        'NetCashFlow': False,
        'NetCashFlowsOperating': False,
        'NetCashFlowsInvesting': False,
        'NetCashFlowsFinancing': False,
        'NetCashFlowsOperatingContinuing': False,
        'NetCashFlowsInvestingContinuing': False,
        'NetCashFlowsFinancingContinuing': False,
        'NetCashFlowsOperatingDiscontinued': False,
        'NetCashFlowsInvestingDiscontinued': False,
        'NetCashFlowsFinancingDiscontinued': False,
        'NetCashFlowsDiscontinued': False,
        'ExchangeGainsLosses': False,
        'Dividends': False,
        'EPS': False
    },
    'calc': {
        'SGR': False,
        'ROA': False,
        'ROE': False,
        'ROS': False,
        'DE': 0
    }
}
